<?php

namespace ProviderBundle\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllProviders()
    {
        return $this->getEntityManager()->createQuery("
        	SELECT p FROM ProviderBundle:Provider p 
            WHERE p.deleted_at IS NULL  ORDER BY p.name ASC
        ")->getResult();
    }
}
