product_color:
    resource: "@ProductBundle/Controller/ColorController.php"
    type:     annotation

import:
    resource: "@ImportBundle/Controller/"
    type:     annotation
    prefix:   /


product_image_product:
    resource: "@ProductBundle/Controller/ImageProductController.php"
    type:     annotation


provider_provider:
    resource: "@ProviderBundle/Controller/ProviderController.php"
    type:     annotation

product_product:
    resource: "@ProductBundle/Controller/ProductController.php"
    type:     annotation

package_package:
    resource: "@PackageBundle/Controller/PackageController.php"
    type:     annotation

category_category:
    resource: "@CategoryBundle/Controller/CategoryController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

category:
    resource: "@CategoryBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

package:
    resource: "@PackageBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

provider:
    resource: "@ProviderBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}
    requirements:
        _locale: en|fr # les locales disponibles, séparées par des pipes « | »

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


