import:
    resource: "@ImportBundle/Controller/"
    type:     annotation
    prefix:   /


product_image_product:
    resource: "@ProductBundle/Controller/ImageProductController.php"
    type:     annotation


provider_provider:
    resource: "@ProviderBundle/Controller/ProviderController.php"
    type:     annotation

product_product:
    resource: "@ProductBundle/Controller/ProductController.php"
    type:     annotation

package_package:
    resource: "@PackageBundle/Controller/PackageController.php"
    type:     annotation

category_category:
    resource: "@CategoryBundle/Controller/CategoryController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

category:
    resource: "@CategoryBundle/Controller/"
    type:     annotation
    prefix:   /

package:
    resource: "@PackageBundle/Controller/"
    type:     annotation
    prefix:   /

provider:
    resource: "@ProviderBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"