# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /fr/login
                check_path:   /fr/login_check
                failure_path: /fr/login
                default_target_path: /fr
                always_use_default_target_path: true
            logout:          
                path:           /fr/logout
                target:         /fr/login
            anonymous:          true

    access_control:
        - { path: ^/fr/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: ROLE_ADMIN }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }




        
