# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/ # c a d tout ce qui commence par / dans l'url va mobiliser le parfeu
            form_login:
                provider: fos_userbundle
                #csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path:   /logout
                target: /login
       
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN } 

        - { path: ^/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }
        
        - { path: ^/register, roles: ROLE_SUPER_ADMIN }
        - { path: ^/product/new, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/category/new, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/package/new, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/provider/new, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }

        - { path: ^/user/[0-9]+/edit/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/product/edit, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }
        - { path: ^/category/edit, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }
        - { path: ^/package/edit, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }
        - { path: ^/provider/edit, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }

        - { path: ^/category/, roles: ROLE_USER }
        - { path: ^/package/, roles: ROLE_USER }
        - { path: ^/provider/, roles: ROLE_USER }
        - { path: ^/provider/, roles: ROLE_USER }
        - { path: ^/provider/, roles: ROLE_USER }