# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
          - { name: form.type, alias: app_user_registration }

    app.form.profile: 
        class: UserBundle\Form\ProfileType
        tags:
          - { name: form.type, alias: app_user_profile }

    import.csvtoarray:
        class: ImportBundle\Services\ConvertCsvToArray