<?php

namespace ProductBundle\Repository;

/**
 * ProductLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLogRepository extends \Doctrine\ORM\EntityRepository
{
}
