<?php

namespace ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllProducts()
    {
        return $this->getEntityManager()->createQuery("
        	SELECT p FROM ProductBundle:Product p left join ProductBundle:ProductLog pl
            WHERE p.id=pl.product AND  pl.action != 'Delete product'  ORDER BY p.name ASC
        ")->getResult();
    }
	
}
